[platformio]
src_dir = src

[env:esp]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32dev
framework = arduino
build_flags=
    ${env.build_flags}
    -DPIN_FLAG1=4
    -DPIN_FLAG2=2
    -DPIN_SESSION_RECORD=13

[env:esp-i2c]
extends = env:esp
build_flags=
    ${env.build_flags}
    -DUSE_I2C_INPUT
    -DPIN_SDA=23
    -DPIN_SCL=19

[env]
build_flags=
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps =
    SPI
    https://github.com/bblanchon/ArduinoJson
