[platformio]
src_dir = src

[env:esp]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
board_build.partitions = min_spiffs.csv
build_flags=
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DINTERNAL_LED_PIN=15
    -DINTERNAL_RGB_LED_PIN=8
    -DPIN_FLAG1=4
    -DPIN_FLAG2=2
    -DPIN_SESSION_RECORD=5

[env:esp-i2c]
extends = env:esp
build_flags=
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DINTERNAL_LED_PIN=15
    -DUSE_I2C_INPUT
    -DPIN_SDA=23
    -DPIN_SCL=19

[env:esp-lite]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = esp32dev
framework = arduino
build_flags=
    ${env.build_flags}
    -DINTERNAL_LED_PIN=22
    -DPIN_FLAG1=4
    -DPIN_FLAG2=2
    -DPIN_SESSION_RECORD=5

[env:esp-lite-i2c]
extends = env:esp-lite
build_flags=
    ${env.build_flags}
    -DINTERNAL_LED_PIN=22
    -DUSE_I2C_INPUT
    -DPIN_SDA=23
    -DPIN_SCL=19

[env:esp-ota]
extra_scripts = platformio_upload.py
upload_protocol = custom
custom_upload_url = http://carrera
extends = env:esp

[env]
build_flags=
    -DFLAGS_PIN=13
lib_deps =
    SPI
    https://github.com/bblanchon/ArduinoJson
    https://github.com/adafruit/Adafruit_NeoPixel@^1.12.0