[platformio]
src_dir = src

[env:esp]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
build_flags=
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DINTERNAL_LED_PIN=15
    -DFLAGS_PIN=0
    -DPIN_SDA=20
    -DPIN_SCL=14

[env]
lib_deps =
    SPI
    https://github.com/bblanchon/ArduinoJson
    https://github.com/sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library
    symlink://../libs/Now
    symlink://../libs/Light
framework = arduino
build_flags=
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
