on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  build-addon:
    name: Build Addon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build --filter @rohmer/cockpit-xp-breakout-board-addon
      - uses: actions/upload-artifact@v4
        with:
          name: addon
          path: packages/addon/dist
  release:
    name: Release Addon
    runs-on: ubuntu-latest
    needs:
      - build-addon
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: addon
          path: packages/addon/dist
      - name: Copy files to dist
        run: | 
          mkdir -p dist/mr-breakout-board-addon
          cp -a packages/addon/dist/. dist/mr-breakout-board-addon
          mkdir -p dist/mr-breakout-board
          cp -a packages/board/src/board dist/mr-breakout-board/
          cp -a packages/board/readme.md dist/mr-breakout-board/
          mkdir -p dist/docs
          cp readme.md dist/mr-breakout-board-addon
          cp -a docs dist/docs
      - name: Zip Assets
        run: |
          cd dist
          zip "../mr-breakout-board-addon" -r ./**
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "mr-breakout-board-addon.zip"
